language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - 1.0.5
  - 1.3.1

matrix:
  allow_failures:
    - julia: nightly

before_script:
    - touch src/study-validated-numerics.jl

notifications:
  email: false